api_platform:
    title: Gymly
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    exception_to_status:
        App\Domain\Shared\Exception\DomainException: 400
